export const GIFF_FETCH_REQUEST = 'GIFF_FETCH_REQUEST';
export const GIFF_FETCH_SUCCESS = 'GIFF_FETCH_SUCCESS';
export const GIFF_FETCH_FAILED = 'GIFF_FETCH_FAILED';

export const GIFF_FETCH_NEXT_PAGE_REQUEST = 'GIFF_FETCH_NEXT_PAGE';
export const GIFF_FETCH_NEXT_PAGE_SUCCESS = 'GIFF_FETCH_NEXT_SUCCESS';
export const GIFF_FETCH_NEXT_PAGE_FAILED = 'GIFF_FETCH_NEXT_FAILED';

export const GIFF_SEARCH_REQUEST = 'GIFF_SEARCH_REQUEST';
export const GIFF_SEARCH_SUCCESS = 'GIFF_SEARCH_SUCCESS';
export const GIFF_SEARCH_FAILED = 'GIFF_SEARCH_FAILED';

export const GIFF_SEARCH_CLEAR = 'GIFF_SEARCH_CLEAR';

export const THEME_TOGGLE = 'THEME_TOGGLE';

export const RESET_GIFF_DATA = 'REST_GIFF_DATA'; 